services:
  app:
    build:
      context: .
    container_name: RiskRealm
    environment:
      - DATABASE_URL=postgresql://${PG_USER}:${PG_PASS}@db:5432/riskrealm
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: riskrealm_db
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=riskrealm
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: